[package]
name = "p8-game"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "project8"
path = "src/main.rs"

[[bin]]
name = "p8-setup"
path = "src/bin/p8-setup.rs"

[dependencies]
bevy.workspace = true
p8-sim.workspace = true
p8-formats.workspace = true
p8-skater.workspace = true
serde_json.workspace = true
